import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NavTab } from './components/navbar'
import { UserProvider } from '@auth0/nextjs-auth0/client';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Event Planning App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <NavTab />
          {children}
        </body>
      </UserProvider>
    </html>
  )
}
